### PR TITLE
Add feature to have horizontal lazy-load

### PR DESCRIPTION
**Pull request by ianwensink**
This PR will add a way to horizontally lazy-load items. This is useful for instance, when working with a carousel.

Also, it fixes an error when using SSR frameworks like Next or react-tree-walker. They offer a way to unmount components on server, which causes react-lazyload to throw a lot of error since window is used in the componentWillUnmount.

### CODE REVIEW

**Comment by svobik7** [comment]
Starving for this PR merge 😃

**Comment by svobik7** [comment]
@ameerthehacker is there any chance to merge this PR?

I think horizontal support is one the top missing features in this great lib.

Thank you.

**Comment by ameerthehacker** [comment]
Nope @svobik7, it looks great @ianwensink Thanks for the contribution, will push a release by this weekend!

**Comment by ameerthehacker** [comment]
@svobik7, @ianwensink can anyone of you create a pull request for updating the docs!

**Comment by svobik7** [comment]
Here #233 it is @ameerthehacker. When would you publish new release, please?

**Comment by ameerthehacker** [comment]
@svobik7 I will try to publish it today @svobik7

**Comment by MandeepKalkhanda** [comment]
@ameerthehacker, waiting for horizontal lazy-load feature. Please publish new release.

**Comment by ameerthehacker** [comment]
@ianwensink, @svobik7, @MandeepKalkhanda , @jasonslyvia, @twobin a new release 2.6.1 has been released to npm which contains support for horizontal scrolling and docks related to the same.

**Comment by jasonslyvia** [comment]
awesome, finally it happens in 2019!

**Comment by hettruong** [comment]
Any demo how to use it?

**Pull request merged**
