### PR TITLE
Allow scroll only x or y

### PR DESCRIPTION
**Pull request by alexandref93**

### CODE REVIEW

**Comment by lidawang** [comment]
This seems like a useful functionality, thoughts on gating this via a prop? I could see use cases where you wouldn't want the logic to behave like this.

**Comment by AmBeta** [comment]
Nice feature, hope to be merged.

**Comment by jasonslyvia** [comment]
I agree with @lidawang , it's better presented as a opt-in prop.

**Comment by AmBeta** [comment]
What about making the option `overflow` to receive an object with the property `x` and `y`. So when a boolean of true is passed in, things work like the current situation. While when an object like `{ x: false, y: true }` is passed in, we can detect the overflow container only with the y axis.  

By the way, when `overflow-x` and `overflow-y` are set different from each other, the `getComputedStyle` API always get an empty string for `overflow`.

**Comment by thonglh** [comment]
For Chrome, `getComputedStyle` API return empty string for `overflow`. So we always get `scrollParent(node) === document`.

Any update here? Can you merge this?

**Pull request closed without merging**
