### PR TITLE
Support for horizontal lazy load in overflow contianer

### PR DESCRIPTION
**Pull request by StoraH**
This in a starting point to support horizontal lazy load
Still some work needs to be done before it can be merge
Todo: 
- **width** prop with same functionality as **height**
- support for window horizontal scroll as well

### CODE REVIEW

**Comment by jasonslyvia** [comment]
hi @StoraH , thanks for your contribution, though I'm really considering using `InstersectionObserver` in replace of current implementation, because it saves us a bunch of options (`height`, `overflow` and more).
See #129 for more information if you're interested.

**Comment by nianiaJR** [comment]
will consider to merge this pr? @ameerthehacker

**Comment by ameerthehacker** [comment]
@nianiaJR before merging this PR I would like to confirm with @StoraH that he has completed the todo and is there anything more to be added to this PR?

**Comment by nianiaJR** [comment]
@ameerthehacker Ok, I'll use the fork one before you finish this，thanks your reply.

**Pull request merged**
