### PR TITLE
Replace findDOMNode with ref

### LINKED ISSUE #209: findDOMNode will be deprecated
Starting from React 16.6 it is deprecated in StrictMode and it will be deprecated from React in the future. [Here](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage) is some more information about this.

The docs state the following:
> Normally you don’t need this because you can attach a ref directly to a DOM node.

The warning in StrictMode:
> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of VisibilitySensor which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

### PR DESCRIPTION
**Pull request by mmarkelov**
Fix #209 
Use ref callback callback to support versions of React described in package.json

### CODE REVIEW

**Comment by ameerthehacker** [comment]
@mmarkelov looks great thanks for the contribution

**Comment by mindctrl** [comment]
@ameerthehacker any plans to release this fix on npmjs?

**Comment by sunknudsen** [comment]
@ameerthehacker `findDOMNode` has been deprecated for a while and this PR hasn’t made it’s way to NPM. Any change you can publish soon?

**Comment by ameerthehacker** [comment]
Yup will do it soon

**Comment by sunknudsen** [comment]
Thanks @ameerthehacker. Much appreciated.

**Comment by sunknudsen** [comment]
Morning @ameerthehacker. Scheduling a release. I understand open source is a product of love so no rush, but do you have an ETA?

**Comment by ameerthehacker** [comment]
@sunknudsen thanks for understanding given the pandemic going it had been difficult to get things together, I'm looking for this weekend for a release. 

Thanks for your patience

**Comment by ameerthehacker** [comment]
@sunknudsen v2.6.6 has been released with this change, do check and let me know

**Comment by sunknudsen** [comment]
Looking good, thanks @ameerthehacker.

**Comment by antbaobao** [comment]
@ameerthehacker cool buddy, thanks

**Comment by ameerthehacker** [comment]
@antbaobao @sunknudsen unfortunately due to some backward compatibility issues we had to roll back the code to findDomNode, I will probably release a beta version of this first so that this does not happen again, and do help me in testing the beta version

**Comment by antbaobao** [comment]
@ameerthehacker take it easy, it's  working fine

**Comment by ameerthehacker** [comment]
@antbaobao thanks
@sunknudsen @antbaobao I have released a beta version to include this change to findDomNode API, please try it as 
```
npm i react-lazyload@beta
```

let me know if all the API's you use work fine

**Comment by kutsan** [comment]
@ameerthehacker Mines work fine FYI.

**Pull request merged**
